
Dozer 集成 Spring Boot

DozerBeanMapperFactoryBean


@startuml
Configuration -> SqlSession: build
SqlSession -> Configuration: getMapper

SqlSession <-- MapperProxy: selectOne
SqlSession --> Executor: query
Executor --> StatementHandler: query
StatementHandler --> ResultSetHandler: HandlerResultSet

@enduml